-- generated by KeySteam
-- update time: 2025-12-09
-- app_name: Ultimate Auto-RPG

addappid(3977070)

addappid(3977071,0,"e1328496d35922e61b0f3f5dce199b1387b36cb6c5412c5f23478acf6ff154fc")
addappid(3992811,0,"73ac7e6cb37b89d77ec63bf819dbe4234ad2c1ac2c524b456062cc8435473009")

addappid(3992810)