-- generated by KeySteam
-- update time: 2026-04-18
-- app_name: 精灵忍者逃走中  3D

addappid(3830690)

addappid(3830691,0,"b7dc6defefd989232eaa64bc1b6251b5e1a5ea073241601dd1d7706eb75376f5")

-- DLC: 0/1
-- missing DLC: 4209540
