-- generated by KeySteam
-- update time: 2026-04-13
-- app_name: OPUS：心相吾山

addappid(1947910)

addappid(1947911,0,"2d774dad6615d2bf47d32919e1d943ad1931ce694beed4a34f250788ba410cfe")

-- DLC: 1/3
-- missing DLC: 4549960, 4549970

addappid(4549980)