-- generated by KeySteam
-- update time: 2026-04-20
-- app_name: Part-Time Witch

addappid(3108980)

addappid(3108981,0,"c2012af5efe84f809a8cddfa507e9958d7a85eec5e1ccfde422bf4cd05efdc67")

-- DLC: 0/3
-- missing DLC: 4082060, 4082070, 4082080
