-- generated by KeySteam
-- update time: 2024-01-12
-- app_name: Zabawa Karaoke

addappid(2183530,0,"1c5f13a6399404f972db409e35a2c6647cc2a514be0d328880213f4c74cbd238")

addappid(2183531,0,"b813e604818bba09d5745ee5d2c204a3e767dcba230b23fabfcdc1d7fdf91df1")
